apiVersion: v1
kind: Template
labels:
  demo: eureka-server-microservice
metadata:
  annotations:
    description: opencapacity demo microservices application buildconfigs template
    iconClass: icon-java
    tags: microservice,jboss,spring
  name: opencapacity-builds
objects:
# opencapacity Eureka
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: eureka-server
    labels:
      comp-required: "true"
      app: eureka-server
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: eureka-server
    labels:
      comp-required: "true"
      app: eureka-server
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: eureka-server:latest
    source:
      contextDir: register-center/eureka-server
      git:
        ref: ${GIT_REF}
        uri: ${GIT_URI}
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: MAVEN_ARGS
          value: package -DskipTests 
        - name: MAVEN_MIRROR_URL
          value: ${MAVEN_MIRROR_URL}
        forcePull: false
        from:
          kind: ImageStreamTag
          namespace: openshift
          name: redhat-openjdk18-openshift:1.2
      type: Source
    resources:
      limits:
        cpu: 500m
        memory: "2Gi"
      requests:
        cpu: "200m"
        memory: "1Gi"

parameters:
- description: Git source URI for application
  displayName: Git source repository
  name: GIT_URI
  required: true
  value: https://github.com/woyaofuwu/open-capacity-f
- description: Git branch/tag reference
  displayName: Git branch/tag reference
  name: GIT_REF
  required: true
  value: 2.0.1
- description: Maven mirror url. If nexus is deployed locally, use nexus url (e.g. http://nexus-cicd-andrew.apps.c918.example.opentlc.com/repository/maven-all-public/)
  displayName: Maven mirror url
  name: MAVEN_MIRROR_URL
- description: NPM mirror url. If nexus is deployed locally, use nexus url (e.g. http://nexus.ci:8081/repository/npm/)
  displayName: NPM mirror url
  name: NPM_MIRROR
- description: Bower mirror url. If nexus is deployed locally, use nexus url (e.g. http://nexus.ci:8081/repository/bower-mirror/)
  displayName: Bower mirror url
  name: BOWER_MIRROR
- description: Decision Server Coolstore Rules Container Spec
  name: KIE_CONTAINER_DEPLOYMENT
  required: true
  value: CoolStoreRulesContainer=com.redhat:coolstore:2.0.0
